"""Phase 1B of the public rulebook expansion: Authentication + Authorization + Input Validation.

Seeds 25 new SEC-AUTH-*, SEC-AUTHZ-*, and SEC-VAL-* rules into Neo4j
(8 mandatory) and renames the legacy SEC-UNI-001 / SEC-UNI-002 rules:

  SEC-UNI-001 (auth+ownership)        -> SEC-AUTHZ-ENFORCE-001
  SEC-UNI-002 (ownership code path)   -> SEC-AUTHZ-IDOR-001

Idempotent. Re-runs MERGE existing rules with the same rule_id.

Per RULEBOOK-AUDIT.md and out-of-the-box-rules.md sections 1B, 1C, 1D.
"""

from __future__ import annotations

import asyncio
from datetime import date

from writ.config import get_neo4j_password, get_neo4j_uri, get_neo4j_user
from writ.graph.db import Neo4jConnection

TODAY = date.today().isoformat()


def _rule(
    rid: str,
    severity: str,
    scope: str,
    trigger: str,
    statement: str,
    violation: str,
    pass_example: str,
    enforcement: str,
    rationale: str,
    mandatory: bool = False,
    mechanical_enforcement_path: str | None = None,
    source_section: str = "1B",
) -> dict:
    return {
        "rule_id": rid,
        "domain": "security",
        "severity": severity,
        "scope": scope,
        "trigger": trigger,
        "statement": statement,
        "violation": violation,
        "pass_example": pass_example,
        "enforcement": enforcement,
        "rationale": rationale,
        "mandatory": mandatory,
        "mechanical_enforcement_path": mechanical_enforcement_path,
        "confidence": "production-validated",
        "authority": "human",
        "times_seen_positive": 0,
        "times_seen_negative": 0,
        "last_validated": TODAY,
        "evidence": "doc:public-rulebook-2026-05",
        "staleness_window": 365,
        "always_on": False,
        "body": "",
        "source_attribution": f"out-of-the-box-rules.md section {source_section}",
        "source_commit": "",
    }


ANALYZER_PATH = "bin/run-analysis.sh::analyze_security_auth_authz"

# ============================================================================
# 1B. Authentication (10 rules, 2 mandatory)
# ============================================================================
AUTH_RULES = [
    _rule(
        "SEC-AUTH-HASH-001",
        "critical",
        "component",
        "When persisting user passwords, password-equivalent secrets, or any credential that must withstand offline cracking.",
        "Passwords must be hashed with bcrypt, argon2, or scrypt. Single-pass MD5, SHA-1, SHA-256, or SHA-512 are never acceptable for password storage. The work factor must match current industry guidance (bcrypt cost >= 12, argon2id memory >= 64 MiB).",
        "```python\nimport hashlib\nhashed = hashlib.sha256(password.encode()).hexdigest()\nuser.password = hashed\n```",
        "```python\nimport bcrypt\nhashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=12))\nuser.password = hashed.decode()\n```",
        f"Mechanically enforced by {ANALYZER_PATH}: regex flags hashlib.md5/sha1/sha256/sha512 (Python), md5()/sha1() (PHP), crypto.createHash('md5'|'sha1'|'sha256') (Node) in proximity to the identifier 'password'/'passwd'/'pwd' or assignment to a *.password field.",
        "Fast hashes are designed for throughput; password hashes must be slow on purpose. GPU rigs crack billions of SHA-256 per second; bcrypt at cost 12 caps adversary throughput by roughly six orders of magnitude. The choice of algorithm is structural, not optional.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
    ),
    _rule(
        "SEC-AUTH-HASH-002",
        "high",
        "component",
        "When generating or storing the salt that accompanies a password hash.",
        "Salts must be unique per user and generated by the hashing library's gensalt helper. Never reuse a global salt, derive the salt from the username, or hand-roll salt generation from a non-CSPRNG.",
        "```python\nSALT = b\"my-app-salt\"\nhashed = bcrypt.hashpw(password.encode() + SALT, bcrypt.gensalt())\n```",
        "```python\nhashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())\n# bcrypt embeds the per-call random salt in its output string.\n```",
        "Code review. Static checks for module-level salt constants or salt = '<literal>' patterns help.",
        "Per-user salts defeat rainbow tables and force the attacker to mount a separate attack per credential. Library-generated salts come from a CSPRNG; hand-rolled salts are routinely weak.",
    ),
    _rule(
        "SEC-AUTH-TIMING-001",
        "high",
        "component",
        "When comparing two byte/string values where one side is attacker-influenced and the other is a secret (session token, API key, password hash, HMAC tag, reset token).",
        "Secret comparisons must use constant-time helpers: Python `hmac.compare_digest`, Node `crypto.timingSafeEqual`, PHP `hash_equals`, Java `MessageDigest.isEqual`. Equality operators (`==`, `===`) leak timing information.",
        "```python\nif user_supplied_token == stored_token:\n    grant_access()\n```",
        "```python\nimport hmac\nif hmac.compare_digest(user_supplied_token.encode(), stored_token.encode()):\n    grant_access()\n```",
        "Code review. Grep for ` == ` or ` === ` adjacent to identifiers containing 'token', 'secret', 'hmac', 'signature', 'mac', 'tag'.",
        "Timing attacks let a remote attacker peel a secret one byte at a time by observing micro-latency. Constant-time comparison closes the side channel structurally.",
    ),
    _rule(
        "SEC-AUTH-TOKEN-001",
        "critical",
        "component",
        "When generating session tokens, password-reset tokens, email-verification tokens, API keys, OAuth state values, CSRF tokens, or any other security-sensitive random value.",
        "Security tokens must be produced by a cryptographically secure pseudo-random number generator: Python `secrets`, Node `crypto.randomBytes`, PHP `random_bytes`, Java `SecureRandom`. The token must be at least 128 bits of entropy (16 random bytes hex-encoded or 22 base64url characters).",
        "```python\nimport random, string\ntoken = ''.join(random.choices(string.ascii_letters + string.digits, k=20))\n```",
        "```python\nimport secrets\ntoken = secrets.token_urlsafe(32)  # 256 bits of entropy\n```",
        f"Mechanically enforced by {ANALYZER_PATH}: regex flags Math.random(), random.random(), random.choices(), random.randint(), random.choice(), rand(), mt_rand(), srand() within proximity to identifiers 'token', 'session', 'secret', 'csrf', 'key', 'nonce', 'reset', 'verify', 'api_key', 'sessid', 'salt'.",
        "`random.random` is seeded by predictable system state and produces predictable streams. Once an attacker recovers a few outputs, they can predict future tokens. CSPRNGs source entropy from the kernel and have no recoverable state.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
    ),
    _rule(
        "SEC-AUTH-TOKEN-002",
        "high",
        "component",
        "When issuing session tokens (cookies, Authorization headers) from the application server.",
        "Session cookies must be set with Secure (HTTPS only), HttpOnly (no JS access), and SameSite=Lax or Strict. Authorization-header bearer tokens are transmitted only to HTTPS endpoints. Plain HTTP transmission of any session credential is forbidden.",
        "```python\nresponse.set_cookie('sessionid', token)\n```",
        "```python\nresponse.set_cookie(\n    'sessionid', token,\n    secure=True, httponly=True, samesite='Lax',\n    max_age=86400,\n)\n```",
        "Framework config review (Django SESSION_COOKIE_SECURE/HTTPONLY/SAMESITE, Flask SESSION_COOKIE_SECURE, Express express-session cookie.secure/httpOnly/sameSite). Static analysis flags `set_cookie` without these flags.",
        "Secure stops MITM credential theft on shared networks. HttpOnly stops XSS-driven cookie exfiltration. SameSite stops cross-site CSRF and some token-leak vectors. All three are zero-cost browser-level defenses.",
    ),
    _rule(
        "SEC-AUTH-MFA-001",
        "medium",
        "component",
        "When implementing TOTP-based multi-factor authentication.",
        "MFA shared secrets must be encrypted at rest (database-level or field-level), never stored in plaintext. TOTP verification accepts only the current 30-second period plus exactly one adjacent period for clock skew. Wider windows are violations.",
        "```python\nuser.totp_secret = generate_secret()\nuser.save()  # plaintext column\nif pyotp.TOTP(secret).verify(code, valid_window=10):\n    pass\n```",
        "```python\nuser.totp_secret = encrypt_at_rest(generate_secret())\nuser.save()\nif pyotp.TOTP(secret).verify(code, valid_window=1):\n    pass\n```",
        "Schema review (encrypted column type), code review (valid_window argument).",
        "A wide TOTP window expands the brute-force keyspace; plaintext secrets give a database leak full account takeover. Both undermine the second factor.",
    ),
    _rule(
        "SEC-AUTH-BRUTE-001",
        "high",
        "component",
        "When implementing any authentication endpoint (login, password verify, MFA verify, API token issuance).",
        "Failed authentication attempts must be rate-limited per account and per source IP. Acceptable mechanisms: progressive lockout (lock for N minutes after K fails), exponential backoff, CAPTCHA after threshold. The limit applies even when the username does not exist.",
        "```python\n@app.route('/login', methods=['POST'])\ndef login():\n    user = User.query.filter_by(email=email).first()\n    if user and user.check_password(password):\n        return success()\n    return error()  # unlimited retries\n```",
        "```python\n@app.route('/login', methods=['POST'])\n@limiter.limit('5 per minute', key_func=lambda: request.json['email'])\n@limiter.limit('20 per minute', key_func=get_remote_address)\ndef login():\n    ...\n```",
        "Code review. Look for auth endpoints without rate-limit decorators or middleware. Frameworks: Flask-Limiter, django-ratelimit, express-rate-limit.",
        "Credential stuffing is automated and cheap. Without a per-account limit, an attacker tries a billion known-password pairs in hours. Per-IP plus per-account limits are the structural defense.",
    ),
    _rule(
        "SEC-AUTH-RESET-001",
        "high",
        "component",
        "When implementing password reset, email change confirmation, or any single-use token-bearing link sent to a user.",
        "Reset tokens must be single-use (invalidated on first successful use), time-limited to one hour or less, and invalidated when the underlying credential changes by any other path. Tokens are CSPRNG-generated per SEC-AUTH-TOKEN-001.",
        "```python\nuser.reset_token = secrets.token_urlsafe(32)\nuser.save()\n# No expiry field; token reusable forever.\n```",
        "```python\nuser.reset_token = secrets.token_urlsafe(32)\nuser.reset_token_expires_at = datetime.utcnow() + timedelta(minutes=30)\nuser.save()\n# Verify side: check token, expiry, mark token consumed.\nuser.reset_token = None\nuser.reset_token_expires_at = None\nuser.save()\n```",
        "Schema review (expiry column, consumed flag), code review (consumption logic).",
        "A reset token without expiry is a permanent backdoor that survives token exposure (email leak, browser history). A non-single-use token can be replayed after the user thinks they have rotated credentials.",
    ),
    _rule(
        "SEC-AUTH-ENUM-001",
        "medium",
        "component",
        "When implementing login, password reset, signup, or any endpoint that distinguishes between 'this account exists' and 'this account does not exist'.",
        "Login and password-reset endpoints must return identical responses (same status, same body, same timing) for valid and invalid accounts. Discoverability of registered usernames or emails is a violation.",
        "```python\nif not user:\n    return 'No such email', 404\nif not user.check_password(password):\n    return 'Wrong password', 401\n```",
        "```python\nif not user or not user.check_password(password):\n    return 'Invalid email or password', 401\n```",
        "Code review. Look for branched error messages or distinct status codes on auth failure paths.",
        "Account enumeration powers targeted phishing, credential stuffing prioritization, and abuse reporting workflows. Uniform responses remove the oracle.",
    ),
    _rule(
        "SEC-AUTH-LOGOUT-001",
        "medium",
        "component",
        "When implementing logout for any session-bearing authentication system.",
        "Logout must invalidate the server-side session: delete the session row, revoke the JWT (if a denylist is maintained), or rotate the session key. Clearing the cookie client-side without server-side invalidation is a violation.",
        "```python\n@app.route('/logout')\ndef logout():\n    response = redirect('/')\n    response.delete_cookie('sessionid')\n    return response\n```",
        "```python\n@app.route('/logout')\ndef logout():\n    session_store.delete(session['sid'])  # server-side invalidation\n    response = redirect('/')\n    response.delete_cookie('sessionid')\n    return response\n```",
        "Code review.",
        "A cookie-only logout leaves the session valid on any other device or in any captured copy of the cookie. Server-side invalidation makes the credential genuinely unusable.",
    ),
]

# ============================================================================
# 1C. Authorization & Access Control (9 rules; 2 renames + 7 new; 4 mandatory)
# ============================================================================
AUTHZ_RULES = [
    _rule(
        "SEC-AUTHZ-ENFORCE-001",
        "critical",
        "component",
        "When defining any HTTP route, RPC handler, GraphQL resolver, or server action.",
        "Every endpoint must declare an explicit authorization check: framework-native auth decorator, dependency, middleware, or in-function check before any business logic runs. 'Open by default' or 'forgot to add auth' is a violation. Public endpoints must be explicitly marked.",
        "```python\n@app.route('/admin/users')\ndef list_users():\n    return User.query.all()\n# No auth check; all callers see all users.\n```",
        "```python\n@app.route('/admin/users')\n@login_required\n@admin_required\ndef list_users():\n    return User.query.all()\n```",
        f"Mechanically enforced by {ANALYZER_PATH}: presence check flags route definitions (@app.route, @app.get/post/put/delete, FastAPI @router.*, Django path()/url()) without an auth decorator or Depends(auth) call in the same handler. Frameworks: Flask-Login, django.contrib.auth, FastAPI Security().",
        "Authorization missed by default is the most common access-control bug. The defense is structural: every endpoint declares its policy explicitly, and CI flags handlers that do not.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-IDOR-001",
        "critical",
        "component",
        "When loading or mutating any record where the record ID is supplied by the request (URL path param, query string, body field).",
        "Object access must be verified against the authenticated user's permissions, not just the existence of the record. Loading `Order.find(params[:id])` without checking `order.user_id == current_user.id` (or equivalent permission predicate) is a violation. This applies to read, update, delete, and side-channel exposure (filenames, redirect targets).",
        "```python\n@app.route('/orders/<int:id>')\n@login_required\ndef view_order(id):\n    order = Order.query.get_or_404(id)\n    return render(order)\n# Any logged-in user can read any order by guessing IDs.\n```",
        "```python\n@app.route('/orders/<int:id>')\n@login_required\ndef view_order(id):\n    order = Order.query.filter_by(id=id, user_id=current_user.id).first_or_404()\n    return render(order)\n```",
        "Code review. Look for `.get(pk=...)`, `Model.find(...)`, `.objects.get(id=...)` where the ID source is request data and no follow-up ownership/permission check is present.",
        "Insecure direct object reference is one of the OWASP Top 10 staples because record-by-ID is the default ORM pattern and the permission check is easy to omit. Every loader of user-influenced IDs must also gate access.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-PRIV-001",
        "high",
        "component",
        "When implementing endpoints that change a user's role, grant admin status, modify another user's permissions, or alter security-relevant account state (email, MFA settings, recovery keys).",
        "Privilege-escalation paths must require re-authentication: a fresh password prompt, MFA challenge, or 'sudo mode' session within the last few minutes. A long-lived session is not sufficient.",
        "```python\n@app.route('/account/promote', methods=['POST'])\n@login_required\ndef promote():\n    target = User.query.get(request.json['user_id'])\n    target.role = 'admin'\n    target.save()\n```",
        "```python\n@app.route('/account/promote', methods=['POST'])\n@login_required\n@reauth_required(max_age=300)  # last password check within 5 minutes\ndef promote():\n    ...\n```",
        "Code review. Look for role/permission mutations without reauth gating.",
        "A stolen session cookie is a credential. Re-auth on privilege-changing actions limits the damage: the attacker may read but cannot escalate without the original password.",
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-SCOPE-001",
        "high",
        "component",
        "When issuing API tokens, OAuth grants, machine-to-machine credentials, or service accounts.",
        "Tokens must carry the minimum scopes required for their use case. Wildcard scopes (`*`, `admin`, `all`) are forbidden except for explicit administrative tooling. Scopes are enforced at the resource server, not assumed by the client.",
        "```python\ntoken = issue_token(user_id=u.id, scopes=['*'])\n```",
        "```python\ntoken = issue_token(user_id=u.id, scopes=['orders:read', 'profile:read'])\n```",
        "Token issuance code review, scope-enforcement middleware review.",
        "Wildcard scopes guarantee that any token leak is a full account takeover. Minimum scopes contain the blast radius of a compromise.",
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-RBAC-001",
        "medium",
        "component",
        "When the application has roles, permissions, or capabilities that gate behavior.",
        "Role checks must happen at the service/controller layer, not only at the route layer. A function that performs a privileged action must reject callers who lack the role, even when invoked from internal code paths.",
        "```python\n# Route-level only:\n@app.route('/admin/users')\n@admin_required\ndef admin_list_users():\n    return list_users()\n\ndef list_users():\n    return User.query.all()  # called from elsewhere without admin check\n```",
        "```python\ndef list_users(actor: User):\n    if not actor.has_role('admin'):\n        raise PermissionDenied()\n    return User.query.all()\n```",
        "Code review. Look for privileged operations whose only guard is a route decorator.",
        "Route-only authorization breaks the moment another caller (background job, internal RPC, another endpoint) reuses the underlying function. Defense-in-depth places the check on the operation itself.",
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-DEFAULT-001",
        "critical",
        "component",
        "When adding a new endpoint, GraphQL field, server action, or admin tool to the application.",
        "New endpoints default to deny: they must opt in to a permission policy. The framework or application middleware must reject requests to endpoints without an explicit policy. 'No decorator means public' is a violation.",
        "```python\n# Framework defaults to allow; new endpoint inherits public access.\n@app.route('/internal/secret-debug')\ndef debug_dump():\n    return all_secrets()\n```",
        "```python\n# App-level middleware rejects any handler without @policy(...) marker.\n@app.route('/internal/secret-debug')\n@policy('admin', reauth=True)\ndef debug_dump():\n    return all_secrets()\n```",
        f"Mechanically enforced by {ANALYZER_PATH}: presence check rejects handlers without an authorization decorator or middleware-tag. Phase 1B implementation flags suspect handlers; full coverage requires framework-aware deny-by-default middleware.",
        "Deny-by-default is the only configuration that fails safe when a developer forgets to think about authorization. Inverting the default turns absence-of-thought into a security finding instead of a silent leak.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-TENANT-001",
        "critical",
        "component",
        "When the application has multiple tenants (organizations, workspaces, accounts) sharing the same database or storage.",
        "Multi-tenant queries must filter by tenant ID at the data layer (repository method, ORM scope, query helper), not only at the API layer. Tenant scoping enforced only in controllers leaks data through internal callers, background jobs, or any code path that bypasses the controller.",
        "```python\n# Controller-only filter:\n@app.route('/orders')\n@login_required\ndef orders():\n    return Order.query.filter_by(org_id=current_user.org_id).all()\n# Background job:\ndef rebuild_index():\n    for o in Order.query.all():  # all tenants leak into the global index\n        index.add(o)\n```",
        "```python\nclass TenantQuery(Query):\n    def with_tenant(self, org_id):\n        return self.filter(self.model.org_id == org_id)\n\nOrder.query.with_tenant(current_user.org_id).all()\n# Repository wrappers enforce the filter at the data layer.\n```",
        "Code review of repositories and ORM scopes. Static analysis can flag raw `Model.query.all()` outside of tenant-scoped wrappers.",
        "Cross-tenant data leaks are the highest-impact authorization bug in SaaS systems: a single missing filter exposes every customer at once. Data-layer enforcement is the structural defense.",
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-FUNC-001",
        "high",
        "component",
        "When implementing administrative functionality alongside regular user functionality in the same application.",
        "Administrative endpoints must be separated by path prefix and middleware (e.g., `/admin/*` behind `require_admin` middleware), not only by UI visibility. Hiding admin controls in the client is not access control.",
        "```python\n# Admin controls hidden in the frontend but accessible at the same /api/users URL with role='admin' in body:\n@app.route('/api/users', methods=['POST'])\ndef create_user():\n    User.create(**request.json)  # role field accepted from any caller\n```",
        "```python\n@app.route('/admin/users', methods=['POST'])\n@admin_required\ndef admin_create_user():\n    User.create(**admin_allowlist(request.json))\n\n@app.route('/users', methods=['POST'])\n@login_required\ndef user_signup():\n    User.create(**user_signup_allowlist(request.json))\n```",
        "Code review of route registration, middleware coverage.",
        "Hidden-not-disabled controls are routinely discovered by inspecting JS bundles or by curling the API directly. Path-and-middleware separation is mechanically enforceable; UI hiding is not enforcement at all.",
        source_section="1C",
    ),
    _rule(
        "SEC-AUTHZ-MASS-001",
        "critical",
        "component",
        "When constructing or updating a model instance from a request body (REST POST/PATCH, GraphQL mutation, form submission).",
        "Model fields populated from user input must use an explicit allowlist (Pydantic schema with declared fields, Rails strong parameters `permit(...)`, Django ModelForm `fields = [...]`, ActiveRecord `params.require(...).permit(...)`). Passing the raw request body to a constructor or update call is a violation.",
        "```python\n# Python\nuser = User(**request.json)  # role, is_admin, balance all accepted from caller\nuser.save()\n```\n```ruby\n# Rails\nuser.update_attributes(params[:user])\n```\n```javascript\n// Node\nObject.assign(user, req.body); user.save();\n```",
        "```python\nclass UserCreate(BaseModel):\n    email: EmailStr\n    name: str\n\nuser = User(**UserCreate(**request.json).dict())\nuser.save()\n```\n```ruby\nuser.update_attributes(params.require(:user).permit(:email, :name))\n```",
        f"Mechanically enforced by {ANALYZER_PATH}: regex flags `Model(**request.json|request.body|req.body)`, `Object.assign(model, req.body)`, `update_attributes(params[`, `Model.create(**request.`. The detector encodes the common mass-assignment idioms across Python, Ruby, and Node.",
        "Mass assignment lets the caller set fields the developer never meant to be writable: role, is_admin, balance, password_hash. The structural defense is an explicit allowlist at the request-binding layer, not field-by-field deny logic.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
        source_section="1C",
    ),
]

# ============================================================================
# 1D. Input Validation & Sanitization (8 rules, 2 mandatory)
# ============================================================================
VAL_RULES = [
    _rule(
        "SEC-VAL-SERVER-001",
        "critical",
        "component",
        "When accepting any data from a client (HTTP request, form, file upload, websocket message, mobile-app payload, third-party webhook).",
        "All input validation is performed server-side, before the data reaches business logic. Client-side validation exists for UX only and is never trusted. Trusting a custom HTTP header or a hidden form field as 'pre-validated' is a violation.",
        "```javascript\n// Frontend\nif (form.email.match(EMAIL_REGEX)) { submit(form); }\n// Backend\napp.post('/signup', (req, res) => {\n  db.users.create(req.body);  // assumes frontend validated\n});\n```",
        "```javascript\n// Backend\napp.post('/signup', (req, res) => {\n  const { error, value } = signupSchema.validate(req.body);\n  if (error) return res.status(400).json({ error });\n  db.users.create(value);\n});\n```",
        f"Mechanically enforced by {ANALYZER_PATH}: presence check flags handler functions that read req.body / request.json directly without an intervening schema-validation call. Detection is conservative; code review covers the rest.",
        "Every byte from the client is hostile until validated. Server-side validation is the only trust boundary that matters; client validation is an accessibility helper, not a security control.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
        source_section="1D",
    ),
    _rule(
        "SEC-VAL-TYPE-001",
        "high",
        "component",
        "When implementing any endpoint that accepts a JSON or form body.",
        "Request payloads must be validated against a typed schema (Pydantic, Marshmallow, Zod, Yup, JSON Schema, Joi, class-validator, Bean Validation) before business logic runs. Hand-rolled `if 'field' in request.json` checks are insufficient.",
        "```python\n@app.route('/api/users', methods=['POST'])\ndef create_user():\n    data = request.json\n    if 'email' in data:\n        User.create(email=data['email'])\n```",
        "```python\nclass UserCreate(BaseModel):\n    email: EmailStr\n    name: constr(max_length=120)\n\n@app.route('/api/users', methods=['POST'])\ndef create_user():\n    payload = UserCreate(**request.json)\n    User.create(**payload.dict())\n```",
        "Code review. Look for handler functions that read request.json/request.body without an immediate schema constructor or validate() call.",
        "Schemas turn validation from a manually-maintained pile of `if` statements into a single declarative source of truth that also generates docs, types, and OpenAPI. The structural win is enormous.",
        source_section="1D",
    ),
    _rule(
        "SEC-VAL-LENGTH-001",
        "high",
        "component",
        "When defining schemas or accepting string-typed fields from user input.",
        "All string inputs must have an explicit maximum length constraint. Unbounded text fields (free-form descriptions, comments, names) without a max_length are violations. The default for any new string field is bounded.",
        "```python\nclass Comment(BaseModel):\n    body: str  # no length cap\n```",
        "```python\nclass Comment(BaseModel):\n    body: constr(min_length=1, max_length=10_000)\n```",
        "Schema review. Look for `str`, `Optional[str]`, `TEXT`/`VARCHAR` columns without length constraints.",
        "Unbounded input fields are a denial-of-service vector (gigabyte payloads) and a database-bloat vector. Length caps are zero-cost and prevent both.",
        source_section="1D",
    ),
    _rule(
        "SEC-VAL-RANGE-001",
        "medium",
        "component",
        "When accepting numeric inputs (counts, IDs, prices, percentages, durations, sizes).",
        "Numeric inputs must be validated against the domain-appropriate range. Negative quantities, integer overflow values, and out-of-domain numbers (e.g., percentage > 100, year < 1900) are rejected at validation time.",
        "```python\nclass Order(BaseModel):\n    quantity: int  # accepts negatives, accepts billions\n    discount_percent: float  # accepts 9999.0\n```",
        "```python\nclass Order(BaseModel):\n    quantity: conint(ge=1, le=10_000)\n    discount_percent: confloat(ge=0.0, le=100.0)\n```",
        "Schema review.",
        "Unbounded numeric inputs are the root of many business-logic bugs: negative-quantity refunds, integer overflows, prices smaller than rounding error. Explicit ranges shut the door.",
        source_section="1D",
    ),
    _rule(
        "SEC-VAL-FILE-001",
        "critical",
        "component",
        "When accepting file uploads from users (avatars, attachments, documents, media).",
        "File uploads must be validated by content (magic bytes / libmagic / file-type sniffing), not just by extension or client-supplied MIME type. Files are stored outside the web root, served through an application handler that sets safe Content-Type and Content-Disposition headers. Filename is sanitized or replaced with a UUID.",
        "```python\n@app.route('/upload', methods=['POST'])\ndef upload():\n    f = request.files['file']\n    if f.filename.endswith('.pdf'):\n        f.save(f'static/uploads/{f.filename}')  # web-root, attacker-controlled name\n```",
        "```python\nimport magic, uuid\n@app.route('/upload', methods=['POST'])\ndef upload():\n    f = request.files['file']\n    mime = magic.from_buffer(f.read(2048), mime=True)\n    if mime not in {'application/pdf', 'image/png', 'image/jpeg'}:\n        abort(400)\n    f.seek(0)\n    storage_name = f'{uuid.uuid4()}.bin'\n    f.save(f'/var/app-uploads/{storage_name}')\n```",
        f"Mechanically enforced by {ANALYZER_PATH}: regex flags `request.files[...].save(`, `$request->file(...)->store(`, `multer({{ dest: ... }})`, and similar patterns to direct manual review.",
        "Extension-only and MIME-only checks are trivially spoofed. Content sniffing closes the spoof; out-of-web-root storage closes the direct-execute vector; sanitized filenames close the path-traversal vector. All three are required.",
        mandatory=True,
        mechanical_enforcement_path=ANALYZER_PATH,
        source_section="1D",
    ),
    _rule(
        "SEC-VAL-REGEX-001",
        "medium",
        "component",
        "When accepting regex patterns from end users (search, filter, advanced query, admin UI).",
        "User-supplied regular expressions must be rejected outright or executed under a non-backtracking engine (RE2, Hyperscan) with a time bound. The default Python `re`, Node `RegExp`, PHP `preg_match`, and Java `Pattern` engines are exposed to ReDoS.",
        "```python\npattern = request.GET.get('pattern')\nmatches = [s for s in items if re.search(pattern, s.name)]\n```",
        "```python\nimport re2  # google-re2 binding\npattern = request.GET.get('pattern')\ntry:\n    compiled = re2.compile(pattern, max_mem=8*1024*1024)\nexcept re2.error:\n    abort(400)\nmatches = [s for s in items if compiled.search(s.name)]\n```",
        "Code review. Look for `re.compile(user_input)` or equivalent patterns.",
        "A catastrophic-backtracking regex can hang a worker for minutes on a single short input. Without a non-backtracking engine or a timeout, this is a single-request denial of service.",
        source_section="1D",
    ),
    _rule(
        "SEC-VAL-ENCODING-001",
        "high",
        "component",
        "When validating any input that may have been URL-encoded, HTML-entity-encoded, or unicode-normalized differently from canonical form.",
        "Input is decoded to canonical form (single decode, NFC unicode normalization) before validation. Double-decoding, accepting mixed encodings, or validating before decoding allows bypass through alternative encodings.",
        "```python\nif '..' in path:  # rejects '..' but accepts '..%2f' or '%2e%2e/'\n    abort(400)\nopen(unquote(path))  # decoded after the check\n```",
        "```python\ncanonical = unicodedata.normalize('NFC', unquote(path))\nif '..' in canonical:\n    abort(400)\nopen(canonical)\n```",
        "Code review. Look for validation followed by decoding/normalization rather than the reverse.",
        "Encoding bypass is one of the oldest WAF-evasion tricks. Canonical-form validation removes the trick by collapsing all encodings to a single representation before the check runs.",
        source_section="1D",
    ),
    _rule(
        "SEC-VAL-ALLOW-001",
        "high",
        "component",
        "When validating inputs whose valid set is enumerable (countries, statuses, roles, file types, sort fields, redirect targets).",
        "Validation uses an allowlist (explicit set of permitted values) whenever the valid set is enumerable. Blocklists (reject these characters/values) are forbidden where allowlists are possible: blocklists are routinely incomplete and silently fail open on unanticipated inputs.",
        "```python\nif '<script>' in user_html or 'javascript:' in user_html:\n    abort(400)\n# Blocklist; bypassed by '<svg onload=...>'.\n```",
        "```python\nALLOWED_TAGS = {'p', 'br', 'em', 'strong', 'a', 'ul', 'li'}\nsanitized = bleach.clean(user_html, tags=ALLOWED_TAGS, attributes={'a': ['href']})\n```",
        "Code review. Look for negative-pattern checks (blocklists) on fields with an enumerable valid set.",
        "Allowlists fail closed: anything not on the list is rejected. Blocklists fail open: anything the author did not anticipate is allowed. The asymmetry favors allowlists structurally.",
        source_section="1D",
    ),
]


RULES = AUTH_RULES + AUTHZ_RULES + VAL_RULES


async def main() -> None:
    db = Neo4jConnection(get_neo4j_uri(), get_neo4j_user(), get_neo4j_password())
    try:
        async with db._driver.session(database=db._database) as session:
            # 1. Rename legacy SEC-UNI-001 -> SEC-AUTHZ-ENFORCE-001 and
            #    SEC-UNI-002 -> SEC-AUTHZ-IDOR-001 by deleting the old IDs.
            #    The new rules below carry the broader public-rulebook semantics;
            #    the prior auth+ownership and ownership-code-path framings are
            #    captured in the new rules' statements and pass examples.
            for legacy in ("SEC-UNI-001", "SEC-UNI-002"):
                result = await session.run(
                    f"MATCH (r:Rule {{rule_id: '{legacy}'}}) DETACH DELETE r RETURN count(r) AS n"
                )
                row = await result.single()
                print(f"DELETED {legacy} (absorbed into 1C public rulebook)")

            # 2. Upsert the 27 SEC-AUTH-*, SEC-AUTHZ-*, SEC-VAL-* rules.
            created = updated = 0
            for rule in RULES:
                result = await session.run(
                    "MATCH (r:Rule {rule_id: $rid}) RETURN r.rule_id AS x", rid=rule["rule_id"]
                )
                exists = await result.single() is not None
                props = {k: v for k, v in rule.items() if k != "rule_id"}
                await session.run(
                    """
                    MERGE (r:Rule {rule_id: $rid})
                    SET r += $props
                    """,
                    rid=rule["rule_id"], props=props,
                )
                if exists:
                    updated += 1
                    print(f"UPDATED {rule['rule_id']:30s} {'[M]' if rule['mandatory'] else '   '} {rule['severity']}")
                else:
                    created += 1
                    print(f"CREATED {rule['rule_id']:30s} {'[M]' if rule['mandatory'] else '   '} {rule['severity']}")

            print()
            print(f"Summary: {created} created, {updated} updated.")

            r = await session.run("MATCH (r:Rule) RETURN count(r) AS n")
            print(f"Total rules: {(await r.single())['n']}")
            r = await session.run("MATCH (r:Rule) WHERE r.mandatory = true RETURN count(r) AS n")
            print(f"Mandatory: {(await r.single())['n']}")
    finally:
        await db.close()


if __name__ == "__main__":
    asyncio.run(main())
